"""Add status column to pedidos

Revision ID: c49de72fec26
Revises: 11c5317506ec
Create Date: 2024-07-09 02:07:25.374044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c49de72fec26'
down_revision: Union[str, None] = '11c5317506ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargas', sa.Column('cod_pedido', sa.Integer(), nullable=False))
    op.drop_column('cargas', 'cod_Pedido')
    op.add_column('entregas', sa.Column('id_entrega', sa.Integer(), nullable=False))
    op.add_column('entregas', sa.Column('cod_pedido', sa.Integer(), nullable=False))
    op.add_column('entregas', sa.Column('nome_comprador', sa.String(length=150), nullable=False))
    op.add_column('entregas', sa.Column('data_entrega', sa.Date(), nullable=False))
    op.add_column('entregas', sa.Column('status_entrega', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'entregas', 'pedidos', ['cod_pedido'], ['cod_pedido'])
    op.drop_column('entregas', 'id_pedido')
    op.drop_column('entregas', 'id_entregas')
    op.drop_column('entregas', 'CEP')
    op.drop_column('entregas', 'status')
    op.drop_column('entregas', 'Frete')
    op.drop_column('entregas', 'Pais')
    op.drop_column('entregas', 'nomeComprador')
    op.create_foreign_key(None, 'estoque', 'produtos', ['id_produto'], ['Id_produto'])
    op.add_column('itens_pedidos', sa.Column('cod_pedido', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'itens_pedidos', 'pedidos', ['cod_pedido'], ['cod_pedido'])
    op.create_foreign_key(None, 'itens_pedidos', 'produtos', ['id_produto'], ['Id_produto'])
    op.drop_column('itens_pedidos', 'cod_Pedido')
    op.add_column('pedidos', sa.Column('status', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pedidos', 'clientes', ['id_cliente'], ['Id_cliente'])
    op.drop_column('pedidos', 'id_itemPedido')
    op.create_index(op.f('ix_produtos_Id_produto'), 'produtos', ['Id_produto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_Id_produto'), table_name='produtos')
    op.add_column('pedidos', sa.Column('id_itemPedido', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_column('pedidos', 'status')
    op.add_column('itens_pedidos', sa.Column('cod_Pedido', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'itens_pedidos', type_='foreignkey')
    op.drop_constraint(None, 'itens_pedidos', type_='foreignkey')
    op.drop_column('itens_pedidos', 'cod_pedido')
    op.drop_constraint(None, 'estoque', type_='foreignkey')
    op.add_column('entregas', sa.Column('nomeComprador', mysql.VARCHAR(collation='latin1_general_ci', length=150), nullable=False))
    op.add_column('entregas', sa.Column('Pais', mysql.VARCHAR(collation='latin1_general_ci', length=20), nullable=False))
    op.add_column('entregas', sa.Column('Frete', mysql.FLOAT(), nullable=False))
    op.add_column('entregas', sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('entregas', sa.Column('CEP', mysql.VARCHAR(collation='latin1_general_ci', length=12), nullable=False))
    op.add_column('entregas', sa.Column('id_entregas', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('entregas', sa.Column('id_pedido', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'entregas', type_='foreignkey')
    op.drop_column('entregas', 'status_entrega')
    op.drop_column('entregas', 'data_entrega')
    op.drop_column('entregas', 'nome_comprador')
    op.drop_column('entregas', 'cod_pedido')
    op.drop_column('entregas', 'id_entrega')
    op.add_column('cargas', sa.Column('cod_Pedido', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('cargas', 'cod_pedido')
    # ### end Alembic commands ###
